### ISSUE TITLE
phpStorm unable to resolve typings

### ISSUE THREAD

**Issue by leereichardt** [stevethedev/vuex-functional#22]
There seems to be no type definitions defined in the package which causes IDE's to not be able to resolve the typings. 

<img width="516" alt="Screenshot 2020-03-02 13 03 50" src="https://user-images.githubusercontent.com/1117892/75636765-6f3f1680-5c86-11ea-8d3f-34d249c080e0.png">

Any ideas?

**Comment by leereichardt** [comment]
Actually. This just seems to be an issue with phpStorm and importing in Vue files. Might be a config issue

**Comment by leereichardt** [comment]
Apologies, I was wrong again. This is still an issue in a standard ts file

**Comment by stevethedev** [comment]
Apologies on the slow turnaround, I've been very, very busy. This should be fixed, please let me know if you have any issues.

**Comment by stevethedev** [comment]
I'm closing on the assumption that the problem was resolved.
