### ISSUE TITLE
Use StoreOptions from vuex

### ISSUE THREAD

**Issue by Stoom** [stevethedev/vuex-functional#24]
As your version of options is not exported, and you're not using the `StoreOptions` from vuex, it's impossible for me to import my current vue store configuration.

**Comment by stevethedev** [comment]
Thank you for letting me know, I'll look into this.

**Comment by stevethedev** [comment]
Sorry for the slow turnaround. This seems like a pretty simple fix and it should be good to go in v1.0.7. Please let me know if you have any further issues.

**Comment by stevethedev** [comment]
I'm closing this issue on the assumption that the problem was resolved.
